### ISSUE TITLE
Make block `withdrawals` a mandatory field

### ISSUE THREAD

**Issue by JacekGlen** [torquem-ch/silkworm#1348]
The Shanghai fork introduced [EIP-4895](https://eips.ethereum.org/EIPS/eip-4895) together with the new `withdrawals` data. According to the EIP and [API spec](https://ethereum.github.io/execution-apis/api-documentation/) this data is non-optional and should be always present even if as an empty array.

Tasks

1. Update `BlockBody` and `BlockHeader` to have non-optional withdrawals and withdrawals_root
2. withdrawals_root should default to kEmptyRoot if not set
3. Update silkworm/node/db/access_layer.cpp to store and retrieve withdrawals: in read_body() add `std::swap(out.withdrawals, body.withdrawals);` and in write_body() add `body_for_storage.withdrawals = body.withdrawals;`
4. Update RPC output in silkworm/silkrpc/json/block.cpp and silkworm/silkrpc/types/block.cpp to always include withdrawals
5. Fix tests
6. Update RLP if necessary

**Comment by yperbasis** [comment]
What about historical blocks before Shanghai? They don't have withdrawals.

**Comment by JacekGlen** [comment]
After the discussion, it was concluded that block validation is enough and no actual code changes are necessary.
