### ISSUE TITLE
Collector file naming may clash on two instances

### ISSUE THREAD

**Issue by AndreaLanfranchi** [torquem-ch/silkworm#140]
If collector is instantiated with a specific working directory all buffer flushed files are named sequentially with 1, 2, 3 etc
Should we have two instances of collector pointing to same directory file naming overlaps amongst the two.

This does not happen if collector is instantiated providing no working directory as in that case set_working_path ensure uniqueness of working directory using temp path + unique name.

**Comment by Giulio2002** [comment]
#143
