### ISSUE TITLE
Ethash PoW block validation

### ISSUE THREAD

**Issue by yperbasis** [torquem-ch/silkworm#144]
As a prerequisite, we should probably restore `ethash` Hunter package. I removed it with PR #115 because it was not compatible with Wasm. Ideally we should find a way to make `ethash` package compatible with Wasm, perhaps using some macros/options, and then revert PR #115.

There's a couple of consensus tests that check Ethash PoW: [wrongMixHash](https://github.com/ethereum/tests/blob/v7.0.0/BlockchainTests/InvalidBlocks/bcInvalidHeaderTest/wrongMixHash.json) & [wrongNonce](https://github.com/ethereum/tests/blob/v7.0.0/BlockchainTests/InvalidBlocks/bcInvalidHeaderTest/wrongNonce.json). Unfortunately, they were removed in the latest release.

**Comment by AndreaLanfranchi** [comment]
Refer to #240
