### ISSUE TITLE
Build issues when building silkrpc with silkworm as a submodule

### ISSUE THREAD

**Issue by tjayrush** [torquem-ch/silkworm#230]
I cloned a fresh copy of `silkworm` and followed the build instructions. The build completed successfully (although there were a few warnings from the `cmake` step.)

I later cloned a fresh copy of `silkrpc` (`git clone --recurse-submodules git@github.com:torquem-ch/silkrpc.git`) which uses `silkworm` as a submodule.

I followed the `silkrpc`'s build instructions, but the `silkworm` build fails because of line 216 in `./silkrpc/silkworm/CMakeLists.txt`.

```
g++-10: error: unrecognized command-line option '-Wthread-safety'
make[2]: *** [silkworm/core/CMakeFiles/silkworm_core.dir/silkworm/chain/blockchain.cpp.o] Error 1
make[1]: *** [silkworm/core/CMakeFiles/silkworm_core.dir/all] Error 2
make: *** [all] Error 2
```

If I comment out that line (in the `silkrpc` repo), the `silkworm` submodule build works and so does `silkrpc`.

Not sure if this issue belongs in `silkworm` or `silkrpc` repos.

**Comment by AndreaLanfranchi** [comment]
That should be on option for CLANG only while you're building with GCC
A test for detected compiler should be enough
