### ISSUE TITLE
State Transition Tests: General and FuzzyVM

### ISSUE THREAD

**Issue by yperbasis** [torquem-ch/silkworm#239]
[State Transition Tests](https://ethereum-tests.readthedocs.io/en/latest/test_types/gstate_tests.html) have been [proposed](https://github.com/ethereum/EIPs/issues/176) back in 2017, and finalized in 2021. This is a powerful tool to test various scenarios of contract execution. Most importantly, the solution is meant to be compatible with all implementations of EVM. 

In 2021, Marius van der Wijden [proposed ](https://mariusvanderwijden.github.io/blog/2021/05/02/FuzzyVM/) using the exact mechanism for fuzzy testing. This has been successfully [utlized](https://github.com/holiman/goevmlab#trophy-list) to find bugs in Geth, Nethermind and Besu clients.

**Comment by JacekGlen** [comment]
Initial findings:
