### ISSUE TITLE
Switch back to external rather than copied ethash

### ISSUE THREAD

**Issue by yperbasis** [torquem-ch/silkworm#296]
Some time ago I copied some code from [ethash](https://github.com/chfast/ethash) into `silkworm/ethash` & `silkworm/support` because ethash didn't comply into WebAssembly. Since then @chfast has added support for WebAssembly compilation into ethash (https://github.com/chfast/ethash/pull/175), so we should revert to using ethash as an external library and remove the copy-pasted code.

For historical info see PR #115 & PR #240.

**Comment by AndreaLanfranchi** [comment]
For tracking purposes: the library embeds also progpow hashing. Is not that much more code but nevertheless we build something we don't actually use with an impact on build times and binary sizes. This said is also worth to mention progpow (not actually the version implemented by @chfast ) has been approved to be "in backpocket" of ethereum (yet getting lower and lower relevance as "the merge" approaches).
