### ISSUE TITLE
Header downloader

### ISSUE THREAD

**Issue by yperbasis** [torquem-ch/silkworm#297]
This figure shows the overall architecture: 
![image](https://user-images.githubusercontent.com/9080285/136594066-ed63d84c-5f34-4344-82f4-8f980df6991d.png)

One component/thread (BlockProvider) is devoted to replay to external requests.
One component (HeaderDownloader) is devoted to chain downloading.

This figure details the  HeaderDownloader structure:

![architecture](https://user-images.githubusercontent.com/9080285/136594134-ffcbfb5c-9518-44a2-98e5-4a2d98ba2e21.png)

**Comment by mriccobene** [comment]
### RPC
We have a class for each rpc of the sentry interface. Each class has this responsibility: prepare & execute a rpc

![image](https://user-images.githubusercontent.com/9080285/127617084-af0c0af7-f715-4bc3-8766-be742e71bc63.png)

### Packets

Messages (=packets) are not specified in the proto of sentry interface, they are in the Erigon code. We have a struct for each packet:

![image](https://user-images.githubusercontent.com/9080285/127618224-f565ff40-f461-4f33-aa08-2f0908267999.png)

### Messages

We have messages that encapsulate:

- incoming packet pre-processing
- outgoing packet pre-processing

(header processing & requesting logic is elsewhere)

![image](https://user-images.githubusercontent.com/9080285/127618371-69ad7a72-8af9-473b-9451-d65d7bd4abff.png)

### Logic and "main"
The other classes are in the picture below:

![image](https://user-images.githubusercontent.com/9080285/127618619-9dda936a-7a50-40c3-9a39-abe67f5c6b45.png)
