### ISSUE TITLE
Move genesis data to separate repo and import as submodule

### ISSUE THREAD

**Issue by AndreaLanfranchi** [torquem-ch/silkworm#298]
Actually, due to size limitazions in Json data, we need to transform genesis Json data into byte arrays.
This process is carried out by a cmake macro which is slow. Besides, being genesis data constant, makes no sense to recreate the arrays on every build. 

Worth move those to a separate repo where we keep and mantain the pre-built byte arrays.

**Comment by yperbasis** [comment]
It doesn't necessarily have to be in a separate repo, can be inside silkworm as well.

**Comment by AndreaLanfranchi** [comment]
Well yes : probably worth build in /cmd a tool faster than bin2h cmake macro and put the output .cpp files into source dirs directly.
Then mod CmakeLists to check for every .json file to have a matching cpp file.
It could work.
