### ISSUE TITLE
Remove tg_api

### ISSUE THREAD

**Issue by yperbasis** [torquem-ch/silkworm#299]
`silkworm/tg_api` was used to allow Turbo-Geth to execute blocks with Silkworm. Since the feature has been removed from Erigon, tg_api is now obsolete and we should remove it, moving the necessary functionality into `silkworm/core/execution` or `db/silkworm/stagesync` or something.

_Warning_: not a good idea if we need tg_api for Akula (see PR #265).

**Comment by AndreaLanfranchi** [comment]
As #265 is closed I will proceed
