### ISSUE TITLE
Computation of hash boundary for block is off by 1 when diff is a power of 2

### ISSUE THREAD

**Issue by AndreaLanfranchi** [torquem-ch/silkworm#399]
With reference of [this code](https://github.com/torquem-ch/silkworm/blob/master/core/silkworm/types/block.cpp#L32-L45) the boundary is computed on a dividend which is set to `2**256 - 1`. The correct dividend instead should be `2**256`.

With this implementation, as @chfast noted, the computed target (aka boundary) is off by 1 when difficulty is axactly a power of 2

```
>>> 2**256//2**53
12855504354071922204335696738729300820177623950262342682411008
>>> (2**256-1)//2**53
12855504354071922204335696738729300820177623950262342682411007
```

**Comment by Giulio2002** [comment]
May i take care of this when i push my last PR on pruning(pruning tool in toolbox)

**Comment by yperbasis** [comment]
> May i take care of this when i push my last PR on pruning(pruning tool in toolbox)

Sure, go for it.

**Comment by Giulio2002** [comment]
#417 should solve it
