### ISSUE TITLE
Avoid excess processing of changesets, logs, receipts when in pruned mode

### ISSUE THREAD

**Issue by Giulio2002** [torquem-ch/silkworm#419]

**Comment by yperbasis** [comment]
Can you elaborate please? We still need to process some recent change sets in the pruned mode to support re-orgs, and some logs and receipts depending on the storage mode, don't we?

**Comment by Giulio2002** [comment]
yes, we do but we can avoid the ones not in `pruning`threshold

**Comment by yperbasis** [comment]
@Giulio2002 Was this issue addressed by PR #420 or there are still thing to do?
