### ISSUE TITLE
LeakSanitizer: memory leaks in node_test

### ISSUE THREAD

**Issue by canepat** [torquem-ch/silkworm#575]
Building Silkworm at commit [e91de27](https://github.com/torquem-ch/silkworm/commit/e91de278030b7ae1ddaaec1f1237be863616b37f) with ASAN enabled and executing `node_test` produces the following outputs:

[LeakSanitizer.log](https://github.com/torquem-ch/silkworm/files/8124152/LeakSanitizer.log)

The memory leaks in unit tests are caused by two different problems:
- `mdbx::cursor_managed` does not define a custom move assignment operator and leaks when an existing instance is assigned a new one returned from `silkworm::db::open_cursor`
- `silkworm::db::parse_prune_mode` returns a new `silkworm::db::PruneMode` instance that receives its constructor arguments by ref and moves them into its own member variables, but moving is defeated by passing-by-ref so the default copy constructor is called for the `BlockAmount` actual arguments. Such arguments are heap-allocated objects released from their `std::unique_ptr`s at call site in `parse_prune_mode`, hence the leak

**Comment by erthink** [comment]
> * `mdbx::cursor_managed` does not define a custom move assignment operator and leaks when an existing instance is assigned a new one returned from `silkworm::db::open_cursor`

Hmm, I will fix this promptly.

**Comment by canepat** [comment]
I've just submitted a closing PR: https://github.com/erthink/libmdbx/pull/270

**Comment by erthink** [comment]
It looks like I just forgot to implement these `mdbx::`'s operators, sorry.
