### ISSUE TITLE
Use built-in popcount 

### ISSUE THREAD

**Issue by AndreaLanfranchi** [torquem-ch/silkworm#620]
`std::bitset<16>(uint16_t).count()` is dramatically slow compared to builtin counterpart popcount
See https://github.com/torquem-ch/silkworm/blob/master/core/silkworm/trie/node.cpp#L93

**Comment by yperbasis** [comment]
Interesting. It seems that gcc optimizes it, while clang does not: https://godbolt.org/z/Ecv45f1v6

**Comment by AndreaLanfranchi** [comment]
For MSVC is even worst https://godbolt.org/z/cz7EfaKv8

**Comment by yperbasis** [comment]
Previously `common/util.hpp` had
```
// TODO[C++20] replace by std::popcount
inline int popcount(unsigned x) {
#ifdef _MSC_VER
  return __popcnt(x);
#else
  return __builtin_popcount(x);
#endif
}
```

Some time ago I replaced it with `std::bitset<16>(uint16_t).count()` under erroneous assumption that it has the same performance.

**Comment by chfast** [comment]
I can add it to intx, but C++20 has it: https://en.cppreference.com/w/cpp/numeric/popcount.

**Comment by chfast** [comment]
Did you know `std::byteswap` is coming to C++23?
