### ISSUE TITLE
libmdbx not found.

### ISSUE THREAD

**Issue by enmohsinali** [torquem-ch/silkworm#635]
The repo [https://github.com/erthink/libmdbx/tree/d5e4c198d8ab8319041d41ce7c6d44b8c7e7c876](https://github.com/erthink/libmdbx/tree/d5e4c198d8ab8319041d41ce7c6d44b8c7e7c876) is not found.

**Comment by AndreaLanfranchi** [comment]
This is due to recent removal of libmdbx from Github.
We've updated the repository by #633 

Please `pull` the repo again and retry your build.
