### ISSUE TITLE
Ancient Data directory

### ISSUE THREAD

**Issue by theSkele** [torquem-ch/silkworm#658]
In OpenEthereum, Geth or Erigon you may specify different locations for chaindata and ancient data.
There seems to be no flag similar to datadir.ancient in silkworm.
My SSD is only 250GB, and I want to keep ancient data on an HDD. Save some of my precious SSD space.
Im wondering, did I just not see something, or is this not a feature yet? Thanks!

**Comment by AndreaLanfranchi** [comment]
> In OpenEthereum, Geth or Erigon 

This is not totally accurate : I don't know precisely about OE and Geth but for sure such an option **does not exist in Erigon** hence does not exist on Silwkworm either (we keep binary database compatibilty with Erigon stable).
The only option Erigon and Silkworm have to offer is _data-pruning_ (via --prune.. CLI arguments) but this implies some data necessary for querying ancient blocks is NOT persisted into database. It seems to me this is not what you're looking for.

**Comment by theSkele** [comment]
I havent actually used Erigon yet, no idea why I thought so, I apologize.
The pruning is not what I was looking for but I appreciate the response, Thanks again!
