### ISSUE TITLE
ecrecover precompile allows EIP-155 style `v` value

### ISSUE THREAD

**Issue by axic** [torquem-ch/silkworm#678]
As discussed in https://github.com/ethereum/yellowpaper/pull/860 the ecrecover precompile only allows `v={27,28}` and no other value.

The precompile code ([here](https://github.com/torquem-ch/silkworm/blob/master/core/silkworm/execution/precompiled.cpp#L58-L66)) calls [ecdsa::is_valid_signature](https://github.com/torquem-ch/silkpre/blob/main/lib/silkpre/y_parity_and_chain_id.cpp#L49) to check `r`/`s` values and [ecdsa::v_to_y_parity_and_chain_id](https://github.com/torquem-ch/silkpre/blob/main/lib/silkpre/y_parity_and_chain_id.cpp#L29) to retrieve the `v` value.

This latter seems to silently allow EIP-155 style `v` values too, which would be against the spec.

**Comment by yperbasis** [comment]
It's not a problem because later the precompile [rejects]( https://github.com/torquem-ch/silkpre/blob/main/lib/silkpre/precompile.cpp#L65) EIP-155 values.

**Comment by axic** [comment]
Oh you mean the `parity_and_id->chain_id != std::nullopt` part? Yeah, it is a bit confusing, but I see all of this has been rewritten/reworked now.
