### ISSUE TITLE
Downloader executable does not stop cleanly

### ISSUE THREAD

**Issue by AndreaLanfranchi** [torquem-ch/silkworm#747]
Noticed `downloader` executable when CTRL+C is hit ends abruptly.
Should expect to reach 
```
cout << "Downloader stage-loop ended\n";
```
But it does not happen: actually is missing
```
SignalHandler::init();  // Trap OS signals
```
at the top of code.

Tried to add that and, after rebuild, relaunched downloader and hit CTRL+C ...
```
  INFO [09-01|13:16:11.651 UTC] [stage-loop    ] [1/16 Headers] Waiting for headers... from=14'249'212
  INFO [09-01|13:16:15.970 UTC] [sentry-stats  ] Peer �G�       �L��)Ğ1��Ј��m�q_��_�B0
0c���&��       ����
�@mk�N�=_����;u connected, active 10
Got SIGINT. Shutting down ...
  INFO [09-01|13:16:24.411 UTC] [sentry-stats  ] Peer ��RN�����6=��K9�k��=t`�����x�|�S���X�
Ζ
```
but downloader keeps chugging as nothing happened ...
Question ... is downloader only a mock or are we missing stopping checks ?

**Comment by mriccobene** [comment]
Downloader command is only for test/dev purpose. Anyway I will fix it.

**Comment by mriccobene** [comment]
This now is fixed.
