### ISSUE TITLE
Worker termination may leave it in Stopping state

### ISSUE THREAD

**Issue by canepat** [torquem-ch/silkworm#777]
A race condition between the `Worker::work` method completion (e.g. caused by an exception) and the `Worker::stop` method called by an external thread may leave the `Worker` in state `Stopping` (as opposed to the expected `Stopped` state).

**Comment by AndreaLanfranchi** [comment]
Yes confirm.
I believe Worker::Stop should be amended as:

```
void Worker::stop(bool wait) {
    if (!thread_) return;
    
    State expected{State::kStarted);
    if(state_.compare_exchange_strong(expected, State::kStopping)) {
        kick();
    }

    if (wait) {
        thread_->join();
        thread_.reset();
    }
}
```

Hope it helps
