### ISSUE TITLE
Suggestion for dbtool

### ISSUE THREAD

**Issue by tjayrush** [torquem-ch/silkworm#79]
I think it would be a good idea to add user confirmation to the `dbtool` silkworm tool for the `clear` and `drop` options and possibly the `compact` option.

I'm concerned that someone (like me -- but luckily not me) will use them without thinking and destroy existing data

When I first looked at `dbtool`, I just assumed it would protect me, but it doesn't.

```
dbtool --datadir <path> clear
```

will wipe away data without asking the user to confirm. It's easy enough to just ask for user confirmation with a default of `no`.

I know this tool isn't intended to be part of any official release, but if it's possible, someone will do it.

**Comment by AndreaLanfranchi** [comment]
@tjayrush 
Agree is not that difficult even though the amount of typing you have to enter to effectively delete a table is quite long and, imho, implies an explicit intention.
This said ... as the tool can clear (drop) multiple tables you'd like to have a confirmation per table or a global one ?
Maybe also a timeout for user input ? Say one launches it and forgets ... it leaves a transaction opened forever.

**Comment by AndreaLanfranchi** [comment]
@tjayrush 
look at https://github.com/torquem-ch/silkworm/blob/lmdb3/cmd/dbtool.cpp#L244-L264
It actually asks for confirmation for every table **unless** `-Y` flag is also set from command line

**Comment by AndreaLanfranchi** [comment]
@tjayrush can we close this or wish to keep it open for further reference ?
