### ISSUE TITLE
Silkworm crashes with "IOT instruction (core dumped)" immediately upon running

### ISSUE THREAD

**Issue by SeeSoftware** [torquem-ch/silkworm#993]
Hello I would like to report an issue I encountered with Silkworm when attempting to run it. After building the project using the provided build guide, I receive an error message "IOT instruction (core dumped)" after executing it.

![image](https://user-images.githubusercontent.com/20211909/232337542-063e12ec-3f38-437f-b6bf-cca6b8cc3246.png)

Upon investigating the cause of the issue, I found that the terminate() function is being called in the std::thread destructor, although I could not identify any further definitive causes.

![image](https://user-images.githubusercontent.com/20211909/232337629-2c82bf98-5e26-41a1-989a-4bcb7baf059a.png)

I appreciate any feedback or guidance you can provide to help me resolve this issue.

Hardware:
- System:
  - Kernel: 6.2.8-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 12.2.1
    - Desktop: awesome v: 4.3 Distro: Arch Linux
- CPU:
  - Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP arch: Zen 3+ rev: 0 cache: L1: 1024 KiB L2: 8 MiB L3: 64 MiB
  - Speed (MHz): avg: 4048
  - Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
- Info:
  - Memory: 125.71 GiB

**Comment by canepat** [comment]
Thanks for reporting!
